version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  vfcommon: voiceflow/common@0.0.13

jobs:
  lint:
    executor: vfcommon/default-executor
    steps:
      - checkout
      - vfcommon/install_node_modules
      - run:
          name: 'Linting Check'
          command: |
            yarn lint

workflows:
  test-and-release:
    jobs:
      - lint:
          context: dev-test
      - vfcommon/release:
          context: dev-test
          requires:
            - lint
          filters:
            branches:
              only: master
